blank_issues_enabled: false
contact_links:
  - name: BurrMill Q&A Forum
    url: https://groups.google.com/forum/#!forum/burrmill-users
    about: BurrMill users Q&A community. You'll find us hanging out there, too!
